# Generated by Django 5.2 on 2025-04-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokan', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
