# Generated by Django 5.2 on 2025-04-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokan', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subcategory',
        ),
    ]
