# Generated by Django 5.2 on 2025-04-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokan', '0005_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='desc',
        ),
    ]
